open module com.github.forax.pro.example.springboot{ 
  //requires org.springframework.boot.starter.data.jpa;
  //requires org.springframework.boot.starter.web;
  
  requires spring.boot;
  requires spring.boot.autoconfigure;
  requires spring.web;
  requires spring.webmvc;
  requires org.apache.tomcat.embed.core;
  requires com.fasterxml.jackson.core;
  requires com.fasterxml.jackson.datatype.jdk8;
  
  // dependencies
  requires spring.context;  // used by generated bytecode
  requires spring.core;     // used by generated bytecode
  requires spring.beans;    // used by generated bytecode
  
  exports com.github.forax.pro.example.springboot to spring.core;
  //opens com.github.forax.pro.example.springboot;
}
