sudo: false
language: java

matrix:
  include:
    - env: DEMO='printer-demo'
    - env: DEMO='spring-demo'

install:
- wget --no-check-certificate https://github.com/forax/pro/releases/download/0.10-19/pro-linux-early-access.zip
- unzip pro-linux-early-access.zip
- export PATH=$PATH:`pwd`/pro/bin

script:
- echo build $DEMO
- cd $DEMO
- pro


