sudo: false
dist: trusty
language: java

install:
- wget --no-check-certificate https://github.com/forax/pro/releases/download/0.10-18/pro-linux-early-access.zip
- unzip pro-linux-early-access.zip

script:
- cd printer-demo
- ../pro/bin/pro
- cd ..
- cd spring-demo
- ../pro/bin/pro
- cd ..


