sudo: false
dist: trusty
language: java

install:
- wget --no-check-certificate https://github.com/forax/pro/releases/download/0.10-18/pro-linux-early-access.zip
- unzip pro-linux-early-access.zip
- export PATH=$PATH:pro/bin

matrix:
  include:
    -env: DEMO='printer-demo'
    -env: DEMO='spring-demo'

script:
- cd $DEMO
- pro


