sudo: false
language: java
jdk: openjdk11

matrix:
  include:
    - env: DEMO='printer-demo'
    - env: DEMO='spring-demo'

install:
- java pro_wrapper.java version
- export PATH=$PATH:`pwd`/pro/bin

script:
- echo build $DEMO
- cd $DEMO
- pro


